"""
app.py — Drone DSS Streamlit Application  |  DSS301 Course
===========================================================
Run:  python -m streamlit run app.py

Pages (README Section 2):
  1. 🏠  Dashboard       — fleet KPIs + 4 charts
  2. 🎯  Dự đoán        — real-time slider prediction + radar chart
  3. 📝  Nhập dữ liệu   — manual form entry → Data/custom_drone_data.csv
  4. 📊  Phân tích drone — per-unit health analysis
  5. 🤖  Model Info      — accuracy, F1, confusion matrix, feature importance

Flight status rules follow README Section 11 exactly.
Saved CSV columns follow README Section 12 exactly.
EmptyDataError fix applied per README Section 13-Error4.
"""

import json
import streamlit as st
import pandas as pd
import numpy as np
import joblib
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path

from ui import (
    load_css,
    render_top_nav,
    render_page_title,
    render_section_label,
    render_metric_card,
    render_metric_with_chart,
    render_risk_score,
    render_result_badge,
    render_banner,
    render_sidebar_header,
    render_sidebar_upgrade_card,
    render_model_accuracy_card,
    render_class_f1_table,
    render_confusion_matrix_heatmap,
    render_feature_importance_chart,
)


# ─────────────────────────────────────────────────────────────
# PAGE CONFIG
# ─────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="Drone DSS | DSS301",
    page_icon="🚁",
    layout="wide",
    initial_sidebar_state="expanded",
)
load_css()


# ─────────────────────────────────────────────────────────────
# PATHS  (README Section 4)
# ─────────────────────────────────────────────────────────────

BASE_DIR         = Path(__file__).resolve().parent
DATA_PATH        = BASE_DIR / "Data" / "drone_data_clean.csv"   # capital D — README Section 13-Error3
CUSTOM_DATA_PATH = BASE_DIR / "Data" / "custom_drone_data.csv"
MODEL_DIR        = BASE_DIR / "Model"


# ─────────────────────────────────────────────────────────────
# COLOUR PALETTE  (unified across all charts)
# ─────────────────────────────────────────────────────────────

_C = {
    "accent":  "#4f63d2",
    "blue":    "#3f8cff",
    "success": "#16a34a",
    "warning": "#d97706",
    "danger":  "#dc2626",
}
_RISK_MAP = {"High": _C["danger"], "Medium": _C["warning"], "Low": _C["success"]}
_SEQ      = [_C["accent"], _C["blue"], _C["warning"], _C["success"]]


# ─────────────────────────────────────────────────────────────
# FEATURES  (README Section 10 — 10 inputs)
# ─────────────────────────────────────────────────────────────

FEATURES = [
    "battery_level",
    "flight_time",
    "signal_strength",
    "temperature",
    "wind_speed",
    "gps_accuracy",
    "altitude",
    "speed",
    "humidity",
    "pressure",
]


# ─────────────────────────────────────────────────────────────
# CACHED LOADERS
# ─────────────────────────────────────────────────────────────

@st.cache_resource
def load_models() -> dict:
    """Load all 3 RF models + label encoders. README Section 8."""
    names = {
        "risk":  "operation_risk_model",
        "maint": "maintenance_action_model",
        "rec":   "recommendation_model",
    }
    return {
        key: (
            joblib.load(MODEL_DIR / f"{name}.joblib"),
            joblib.load(MODEL_DIR / f"{name}_label_encoder.joblib"),
        )
        for key, name in names.items()
    }


@st.cache_data
def load_data() -> pd.DataFrame:
    """Load drone_data_clean.csv. README Section 4."""
    return pd.read_csv(DATA_PATH)


@st.cache_data
def load_metrics(model_name: str) -> dict | None:
    """Load _metrics.json generated by train_model.py (extended output)."""
    path = MODEL_DIR / f"{model_name}_metrics.json"
    if not path.exists():
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


@st.cache_data
def load_feature_importance() -> pd.DataFrame | None:
    """Load feature_importance.csv generated by train_model.py (extended output)."""
    path = MODEL_DIR / "feature_importance.csv"
    if not path.exists():
        return None
    return pd.read_csv(path)


# ─────────────────────────────────────────────────────────────
# STARTUP — load data + models, show errors if missing
# ─────────────────────────────────────────────────────────────

try:
    models = load_models()
    df     = load_data()
except FileNotFoundError as e:
    render_banner(
        "Không tìm thấy file data hoặc model.  "
        "Kiểm tra thư mục Data/ và Model/, sau đó chạy:  `python train_model.py`",
        "danger",
    )
    st.code(str(e))
    st.stop()
except Exception as e:
    render_banner("Lỗi không xác định khi tải dữ liệu hoặc model.", "danger")
    st.code(str(e))
    st.stop()


# ─────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ─────────────────────────────────────────────────────────────

def build_input_df(**kw) -> pd.DataFrame:
    """Build a single-row DataFrame from keyword args (must match FEATURES)."""
    return pd.DataFrame([{k: kw[k] for k in FEATURES}])


def predict_drone(inp: pd.DataFrame) -> tuple[str, str, str, float]:
    """
    Run all 3 classifiers.
    Returns (operation_risk, maintenance_action, recommendation, confidence%).
    README Section 10.
    """
    X = inp[FEATURES]
    rf_r,  le_r  = models["risk"]
    rf_m,  le_m  = models["maint"]
    rf_rc, le_rc = models["rec"]

    risk  = le_r.inverse_transform(rf_r.predict(X))[0]
    maint = le_m.inverse_transform(rf_m.predict(X))[0]
    rec   = le_rc.inverse_transform(rf_rc.predict(X))[0]

    conf = 0.0
    if hasattr(rf_r, "predict_proba"):
        conf = round(float(rf_r.predict_proba(X).max()) * 100, 1)

    return risk, maint, rec, conf


def flight_decision(battery: float, signal: float, wind: float, gps: float,
                    flight_time: float, temp: float, alt: float, speed: float,
                    risk: str, maint: str) -> tuple[str, str, str]:
    """
    Rule-based flight status layer on top of ML predictions.
    Thresholds from README Section 11 (Risk Conditions table) — exact match.

    Returns (flight_status_label, reason_text, alert_level).

    Priority order (most severe first):
      1. Cấm Bay          — hard safety limits exceeded
      2. Yêu Cầu Bảo Trì — model predicted maintenance needed
      3. Quay Về Trạm     — model predicted High risk
      4. Bay Kèm Giám Sát — soft monitoring thresholds exceeded
      5. Đủ Điều Kiện Bay — all clear
    """
    ml = str(maint).lower()

    # ── Level 1: Cấm Bay (README Section 11 — dangerous conditions) ──
    reasons_critical = []
    if battery < 20:
        reasons_critical.append("pin dưới 20%")
    if signal < 35:
        reasons_critical.append("tín hiệu dưới 35%")
    if wind > 35:
        reasons_critical.append("gió trên 35 m/s")
    if gps > 10:
        reasons_critical.append("GPS accuracy trên 10 m")
    if temp > 45:
        reasons_critical.append("nhiệt độ trên 45°C")
    if temp < -10:
        reasons_critical.append("nhiệt độ dưới -10°C")

    if reasons_critical:
        reason = "Điều kiện nguy hiểm: " + ", ".join(reasons_critical) + "."
        return "Cấm Bay", reason, "danger"

    # ── Level 2: Yêu Cầu Bảo Trì ──────────────────────────────────────
    if any(kw in ml for kw in ("maintenance required", "inspection recommended", "inspect", "urgent")):
        return (
            "Yêu Cầu Bảo Trì",
            "Drone cần kiểm tra hoặc bảo trì trước chuyến bay tiếp theo.",
            "danger",
        )

    # ── Level 3: Quay Về Trạm ──────────────────────────────────────────
    if risk == "High":
        return (
            "Quay Về Trạm",
            "Rủi ro vận hành cao. Drone nên quay về trạm để kiểm tra.",
            "warning",
        )

    # ── Level 4: Bay Kèm Giám Sát (README Section 11 — monitoring thresholds) ──
    reasons_monitor = []
    if flight_time > 40:
        reasons_monitor.append("thời gian bay trên 40 phút")
    if alt > 350:
        reasons_monitor.append("độ cao trên 350 m")
    if speed > 75:
        reasons_monitor.append("tốc độ trên 75")
    if battery < 40:
        reasons_monitor.append("pin dưới 40%")
    if signal < 60:
        reasons_monitor.append("tín hiệu dưới 60%")
    if wind > 25:
        reasons_monitor.append("gió trên 25 m/s")
    if gps > 7:
        reasons_monitor.append("GPS accuracy trên 7 m")

    if reasons_monitor:
        reason = "Cần theo dõi sát: " + ", ".join(reasons_monitor) + "."
        return "Bay Kèm Giám Sát", reason, "warning"

    # ── Level 5: Đủ Điều Kiện Bay ──────────────────────────────────────
    return "Đủ Điều Kiện Bay", "Drone đủ điều kiện vận hành bình thường.", "success"


def battery_status(level: float) -> tuple[str, str]:
    """(label, alert_level). README Section 11 thresholds."""
    if level > 40:
        return "Tốt", "success"
    if level > 20:
        return "Trung Bình", "warning"
    return "Yếu", "danger"


def risk_to_level(risk: str) -> str:
    return {"High": "danger", "Medium": "warning", "Low": "success"}.get(risk, "info")


# Vietnamese display labels
_VN_RISK = {"High": "Nguy Hiểm", "Medium": "Cảnh Báo", "Low": "An Toàn"}
_VN_MAINT = {
    "No maintenance required": "Không yêu cầu bảo trì",
    "Inspection recommended":  "Khuyến nghị kiểm tra",
    "Maintenance required":    "Yêu cầu bảo trì",
    "Monitor":                 "Cần giám sát chặt",
}


def translate(risk: str, maint: str) -> tuple[str, str]:
    return _VN_RISK.get(risk, risk), _VN_MAINT.get(maint, maint)


def risk_score_estimate(battery: float, wind: float,
                         signal: float, temp: float) -> float:
    """Weighted estimate of risk score 0–10 for display on Prediction page."""
    return min(10.0, round(
        (1 - battery / 100) * 4.0
        + (wind / 50)        * 3.0
        + (1 - signal / 100) * 2.0
        + (abs(temp) / 50)   * 1.0,
        1,
    ))


def save_custom(drone_id: str, inp: pd.DataFrame,
                risk: str, maint: str, rec: str,
                bat_label: str, status: str, reason: str) -> pd.DataFrame:
    """
    Append prediction result to custom_drone_data.csv.
    Saved columns follow README Section 12 exactly (18 columns):
      drone_id, battery_level, flight_time, signal_strength, temperature,
      wind_speed, gps_accuracy, altitude, speed, humidity, pressure,
      operation_risk, maintenance_action, recommendation,
      battery_status, flight_status, flight_reason, created_at

    Fix for README Section 13-Error4:
      Handles empty file gracefully — does not raise EmptyDataError.
    """
    row = inp.copy()
    row.insert(0, "drone_id", drone_id)
    # Prediction columns (README Section 12)
    row["operation_risk"]     = risk
    row["maintenance_action"] = maint
    row["recommendation"]     = rec
    row["battery_status"]     = bat_label
    row["flight_status"]      = status
    row["flight_reason"]      = reason
    row["created_at"]         = pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S")

    CUSTOM_DATA_PATH.parent.mkdir(parents=True, exist_ok=True)

    # README Section 13-Error4: safe append — handle empty / missing file
    if CUSTOM_DATA_PATH.exists() and CUSTOM_DATA_PATH.stat().st_size > 0:
        try:
            old = pd.read_csv(CUSTOM_DATA_PATH)
            if not old.empty:
                row = pd.concat([old, row], ignore_index=True)
        except (pd.errors.EmptyDataError, Exception):
            # File exists but is corrupt / truly empty → start fresh
            pass

    row.to_csv(CUSTOM_DATA_PATH, index=False, encoding="utf-8-sig")
    return row


def style_chart(fig: go.Figure, height: int = None) -> go.Figure:
    """Unified Plotly theme — Inter font, near-transparent grid, no frame."""
    fig.update_layout(
        template="plotly_white",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color="#64697a", family="Inter, system-ui, sans-serif", size=12),
        margin=dict(t=28, b=16, l=12, r=12),
        legend=dict(
            bgcolor="rgba(255,255,255,.8)",
            bordercolor="rgba(0,0,0,.06)",
            borderwidth=1,
            font=dict(color="#1c1e2e", size=11),
        ),
        **({"height": height} if height else {}),
    )
    fig.update_xaxes(gridcolor="rgba(0,0,0,.04)", zerolinecolor="rgba(0,0,0,.04)",
                     linecolor="rgba(0,0,0,.08)")
    fig.update_yaxes(gridcolor="rgba(0,0,0,.04)", zerolinecolor="rgba(0,0,0,.04)",
                     linecolor="rgba(0,0,0,.08)")
    return fig


def make_radar_chart(params: dict, safe_threshold: float = 0.6) -> go.Figure:
    """
    Radar chart comparing current normalised values vs safe threshold.
    params: {label: value_0_to_1}
    """
    labels = list(params.keys())
    vals   = [round(v, 3) for v in params.values()]
    # Close the polygon
    labels_c = labels + [labels[0]]
    vals_c   = vals + [vals[0]]
    thresh_c = [safe_threshold] * len(labels_c)

    fig = go.Figure()
    fig.add_trace(go.Scatterpolar(
        r=thresh_c, theta=labels_c,
        fill="toself", fillcolor="rgba(22,163,74,.08)",
        line=dict(color="rgba(22,163,74,.4)", width=1.5, dash="dot"),
        name="Ngưỡng an toàn",
    ))
    fig.add_trace(go.Scatterpolar(
        r=vals_c, theta=labels_c,
        fill="toself", fillcolor="rgba(79,99,210,.15)",
        line=dict(color="#4f63d2", width=2.5),
        name="Thông số hiện tại",
        marker=dict(size=6, color="#4f63d2"),
    ))
    fig.update_layout(
        polar=dict(
            bgcolor="rgba(0,0,0,0)",
            radialaxis=dict(visible=True, range=[0, 1],
                            tickfont=dict(size=9, color="#9da3b5"),
                            gridcolor="rgba(0,0,0,.06)", linecolor="rgba(0,0,0,.08)"),
            angularaxis=dict(tickfont=dict(size=10, color="#1c1e2e"),
                             gridcolor="rgba(0,0,0,.06)", linecolor="rgba(0,0,0,.08)"),
        ),
        legend=dict(font=dict(size=11, color="#64697a"), bgcolor="rgba(0,0,0,0)",
                    orientation="h", y=-0.15),
        margin=dict(t=24, b=50, l=40, r=40),
        height=340,
        paper_bgcolor="rgba(0,0,0,0)",
        font=dict(family="Inter, system-ui"),
    )
    return fig


# ─────────────────────────────────────────────────────────────
# SIDEBAR
# ─────────────────────────────────────────────────────────────

with st.sidebar:
    render_sidebar_header()

    st.markdown(
        "<p style='font-size:.62rem;font-weight:700;text-transform:uppercase;"
        "letter-spacing:.08em;color:rgba(255,255,255,.28);margin:0 0 8px 4px;'>"
        "Navigation</p>",
        unsafe_allow_html=True,
    )

    # README Section 2 — 4 pages (+ Model Info as bonus page 5)
    page = st.radio(
        "Navigation",
        [
            "🏠  Dashboard",
            "🎯  Dự đoán",
            "📝  Nhập dữ liệu",
            "📊  Phân tích drone",
            "🤖  Model Info",
        ],
        label_visibility="collapsed",
    )

    render_sidebar_upgrade_card()


# ─────────────────────────────────────────────────────────────
# TOP NAV BAR
# ─────────────────────────────────────────────────────────────

render_top_nav()


# ─────────────────────────────────────────────────────────────
# PAGE 1 — DASHBOARD  (README Section 2.1)
# ─────────────────────────────────────────────────────────────

if page == "🏠  Dashboard":
    render_page_title(
        "System Overview",
        "Tổng quan dữ liệu vận hành, phân phối rủi ro và hành động bảo trì.  ·  DSS301",
    )

    # ── KPI row (README Section 2.1) ────────────────────────
    avg_score      = float(df["risk_score"].mean())
    high_pct       = round(df["is_high_risk"].mean() * 100, 1)
    avg_risk_level = "High" if avg_score >= 6 else "Medium" if avg_score >= 3 else "Low"

    rng = np.random.default_rng(42)
    k1, k2, k3, k4 = st.columns(4, gap="large")
    with k1:
        render_metric_with_chart(
            "Tổng Bản Ghi", f"{len(df):,}",
            rng.normal(0, 1, 14).cumsum(), _C["accent"], "+3.2% tuần này",
        )
    with k2:
        rng2 = np.random.default_rng(7)
        render_metric_with_chart(
            "Số Drone", str(df["drone_id"].nunique()),
            rng2.normal(0, 1, 14).cumsum(), _C["blue"], "Active units",
        )
    with k3:
        render_metric_card(
            "Tỷ lệ High Risk", f"{high_pct}%",
            "Drone cần xử lý cảnh báo", "−2% so tuần trước",
        )
    with k4:
        render_risk_score(
            round(avg_score, 1), avg_risk_level,
            "Điểm rủi ro trung bình hệ thống",
        )

    st.divider()

    # ── Chart row 1 ─────────────────────────────────────────
    ch1, ch2 = st.columns(2, gap="large")
    with ch1:
        # README Section 2.1: risk score distribution
        render_section_label("Phân phối rủi ro")
        fig = px.histogram(
            df, x="risk_score", color="operation_risk", nbins=11,
            color_discrete_map=_RISK_MAP, barmode="overlay", opacity=0.82,
        )
        fig.update_traces(marker_line_width=0)
        st.plotly_chart(style_chart(fig, 340), use_container_width=True)

    with ch2:
        # README Section 2.1: maintenance action distribution
        render_section_label("Hành động bảo trì")
        mc = df["maintenance_action"].value_counts().reset_index()
        mc.columns = ["action", "count"]
        fig2 = px.bar(mc, x="count", y="action", orientation="h",
                      color="action", color_discrete_sequence=_SEQ)
        fig2.update_layout(showlegend=False, yaxis_title=None, xaxis_title=None)
        fig2.update_traces(marker_line_width=0)
        st.plotly_chart(style_chart(fig2, 340), use_container_width=True)

    # ── Chart row 2 ─────────────────────────────────────────
    ch3, ch4 = st.columns(2, gap="large")
    with ch3:
        # README Section 2.1: battery level vs wind speed
        render_section_label("Battery vs Wind Speed")
        sample = df.sample(min(3000, len(df)), random_state=42)
        fig3 = px.scatter(sample, x="battery_level", y="wind_speed",
                          color="operation_risk", opacity=0.55,
                          color_discrete_map=_RISK_MAP)
        st.plotly_chart(style_chart(fig3, 360), use_container_width=True)

    with ch4:
        # README Section 2.1: average risk score by drone
        render_section_label("Rủi ro trung bình theo drone")
        drone_avg = df.groupby("drone_id")["risk_score"].mean().reset_index()
        fig4 = px.bar(drone_avg, x="drone_id", y="risk_score",
                      color="risk_score",
                      color_continuous_scale=["#dcfce7", "#fef3c7", "#fee2e2"])
        fig4.update_traces(marker_line_width=0)
        fig4.update_layout(coloraxis_showscale=False, xaxis_title=None)
        st.plotly_chart(style_chart(fig4, 360), use_container_width=True)


# ─────────────────────────────────────────────────────────────
# PAGE 2 — DỰ ĐOÁN  (README Section 2.2)
# ─────────────────────────────────────────────────────────────

elif page == "🎯  Dự đoán":
    render_page_title(
        "Real-time Prediction",
        "Điều chỉnh thông số → hệ thống dự đoán tức thì.  ·  README Section 2.2",
    )
    render_banner("Kết quả cập nhật ngay khi bạn di chuyển bất kỳ slider nào.", "info")

    # ── 10 sliders (README Section 10) ──────────────────────
    render_section_label("Thông số đầu vào  (10 features)")
    sl1, sl2 = st.columns(2, gap="large")

    with sl1:
        battery_level   = st.slider("🔋 Pin còn lại (%)",           0.0, 100.0,  60.0, 1.0)
        wind_speed      = st.slider("💨 Tốc độ gió (m/s)",          0.0,  50.0,  15.0, 0.5)
        signal_strength = st.slider("📶 Cường độ tín hiệu (%)",     0.0, 100.0,  70.0, 1.0)
        temperature     = st.slider("🌡️ Nhiệt độ (°C)",            -40.0, 50.0,  25.0, 0.5)
        gps_accuracy    = st.slider("📍 GPS accuracy (m)",           0.0,  10.0,   5.0, 0.1)

    with sl2:
        flight_time = st.slider("⏱️ Thời gian bay (phút)",      0.0,  60.0,  30.0, 0.5)
        altitude    = st.slider("🏔️ Độ cao (m)",                0.0, 500.0, 250.0, 5.0)
        speed       = st.slider("🚀 Tốc độ bay",                 0.0, 100.0,  50.0, 1.0)
        humidity    = st.slider("💧 Độ ẩm (%)",                  0.0, 100.0,  50.0, 1.0)
        pressure    = st.slider("🌬️ Áp suất (hPa)",           950.0,1050.0,1000.0, 1.0)

    # ── Predict ──────────────────────────────────────────────
    inp = build_input_df(
        battery_level=battery_level, flight_time=flight_time,
        signal_strength=signal_strength, temperature=temperature,
        wind_speed=wind_speed, gps_accuracy=gps_accuracy,
        altitude=altitude, speed=speed, humidity=humidity, pressure=pressure,
    )
    risk_pred, maint_pred, rec_pred, conf = predict_drone(inp)
    flight_st, flight_reason, flight_lv  = flight_decision(
        battery_level, signal_strength, wind_speed, gps_accuracy,
        flight_time, temperature, altitude, speed, risk_pred, maint_pred,
    )
    risk_vn, maint_vn  = translate(risk_pred, maint_pred)
    bat_label, bat_lv  = battery_status(battery_level)
    est_score          = risk_score_estimate(battery_level, wind_speed, signal_strength, temperature)

    # ── Output ───────────────────────────────────────────────
    st.divider()
    render_section_label("Kết quả dự đoán  (README Section 2.2)")

    col_score, col_radar = st.columns([1, 1], gap="large")

    with col_score:
        render_risk_score(est_score, risk_pred, f"Model confidence: {conf}%")

        st.markdown("<div style='margin-top:12px'></div>", unsafe_allow_html=True)
        b1, b2 = st.columns(2)
        with b1: render_result_badge("Mức rủi ro",     risk_vn,   risk_to_level(risk_pred))
        with b2: render_result_badge("Tình trạng pin", bat_label, bat_lv)

        b3, b4 = st.columns(2)
        with b3: render_result_badge("Bảo trì",        maint_vn,  "info")
        with b4: render_result_badge("Trạng thái bay", flight_st, flight_lv)

    with col_radar:
        render_section_label("Radar — thông số chuẩn hoá 0–1")
        # Normalise: high = safe for battery/signal; high = risky for others → invert
        params = {
            "Pin":      battery_level / 100,
            "Tín hiệu": signal_strength / 100,
            "GPS":       1 - gps_accuracy / 10,
            "Gió":       1 - wind_speed / 50,
            "Bay":       1 - flight_time / 60,
            "Độ cao":   1 - altitude / 500,
            "Tốc độ":   1 - speed / 100,
            "Nhiệt độ": 1 - abs(temperature - 20) / 65,
        }
        st.plotly_chart(
            make_radar_chart(params, safe_threshold=0.6),
            use_container_width=True,
            config={"displayModeBar": False},
        )

    render_banner(flight_reason, flight_lv)

    st.divider()
    render_section_label("Khuyến nghị cuối cùng")
    render_banner(rec_pred, risk_to_level(risk_pred))


# ─────────────────────────────────────────────────────────────
# PAGE 3 — NHẬP DỮ LIỆU  (README Section 2.3)
# ─────────────────────────────────────────────────────────────

elif page == "📝  Nhập dữ liệu":
    render_page_title(
        "Manual Drone Data Input",
        "Nhập dữ liệu thực địa → dự đoán → lưu vào Data/custom_drone_data.csv  ·  README Section 2.3",
    )

    with st.form("drone_manual_form"):
        render_section_label("Thông tin thiết bị")
        drone_id = st.text_input("Drone ID", value="Drone_Custom_001",
                                 help="Mã định danh drone, ví dụ: Drone_001, UAV_Alpha")

        render_section_label("Thông số cảm biến  (10 features — README Section 10)")
        f1, f2 = st.columns(2, gap="large")
        with f1:
            battery_level   = st.number_input("🔋 Pin còn lại (%)",        0.0, 100.0,  60.0, 1.0)
            flight_time     = st.number_input("⏱️ Thời gian bay (phút)",    0.0, 300.0,  30.0, 1.0)
            signal_strength = st.number_input("📶 Cường độ tín hiệu (%)",  0.0, 100.0,  70.0, 1.0)
            temperature     = st.number_input("🌡️ Nhiệt độ (°C)",         -50.0,  80.0,  25.0, 0.5)
            wind_speed      = st.number_input("💨 Tốc độ gió (m/s)",        0.0, 100.0,  15.0, 0.5)
        with f2:
            gps_accuracy = st.number_input("📍 GPS accuracy (m)",    0.0,  50.0,   5.0, 0.1)
            altitude     = st.number_input("🏔️ Độ cao (m)",          0.0,1000.0, 250.0, 5.0)
            speed        = st.number_input("🚀 Tốc độ bay",           0.0, 200.0,  50.0, 1.0)
            humidity     = st.number_input("💧 Độ ẩm (%)",            0.0, 100.0,  50.0, 1.0)
            pressure     = st.number_input("🌬️ Áp suất (hPa)",     900.0,1100.0,1000.0, 1.0)

        # README Section 2.3 — button label matches README
        submitted = st.form_submit_button("Predict & Save", type="primary")

    if submitted:
        inp = build_input_df(
            battery_level=battery_level, flight_time=flight_time,
            signal_strength=signal_strength, temperature=temperature,
            wind_speed=wind_speed, gps_accuracy=gps_accuracy,
            altitude=altitude, speed=speed, humidity=humidity, pressure=pressure,
        )

        # README Section 2.3 — prediction steps 1–5
        risk_pred, maint_pred, rec_pred, conf = predict_drone(inp)          # step 1+2
        flight_st, flight_reason, flight_lv  = flight_decision(             # step 4
            battery_level, signal_strength, wind_speed, gps_accuracy,
            flight_time, temperature, altitude, speed, risk_pred, maint_pred,
        )
        risk_vn, maint_vn = translate(risk_pred, maint_pred)
        bat_label, bat_lv = battery_status(battery_level)                   # step 3

        saved = save_custom(                                                 # step 6
            drone_id, inp, risk_pred, maint_pred, rec_pred,
            bat_label, flight_st, flight_reason,
        )

        render_banner(
            f"✅ Dự đoán hoàn tất — **{drone_id}** đã được lưu vào Data/custom_drone_data.csv.",
            "success",
        )

        # README Section 2.3 steps output
        render_section_label("Kết quả  (6 bước — README Section 2.3)")
        r1, r2, r3, r4 = st.columns(4, gap="large")
        with r1: render_result_badge("Rủi ro vận hành",  risk_vn,   risk_to_level(risk_pred))
        with r2: render_result_badge("Hành động bảo trì", maint_vn, "info")
        with r3: render_result_badge("Tình trạng pin",   bat_label, bat_lv)
        with r4: render_result_badge("Trạng thái bay",   flight_st, flight_lv)

        render_banner(flight_reason, flight_lv)
        render_banner(rec_pred, risk_to_level(risk_pred))   # step 5: recommendation

        # README Section 12 — show saved row (18 columns)
        with st.expander("📄 Xem bản ghi vừa lưu  (18 cột — README Section 12)"):
            st.dataframe(saved.tail(1), use_container_width=True)
            st.caption(
                f"File: Data/custom_drone_data.csv  ·  "
                f"Tổng bản ghi hiện tại: {len(saved):,}"
            )


# ─────────────────────────────────────────────────────────────
# PAGE 4 — PHÂN TÍCH DRONE  (README Section 2.4)
# ─────────────────────────────────────────────────────────────

elif page == "📊  Phân tích drone":
    render_page_title(
        "Drone Unit Analysis",
        "Theo dõi sức khỏe và lịch sử bảo trì theo từng thiết bị.  ·  README Section 2.4",
    )

    render_section_label("Chọn thiết bị")
    drone_sel = st.selectbox(
        "Drone", sorted(df["drone_id"].unique()), label_visibility="collapsed"
    )
    df_d = df[df["drone_id"] == drone_sel]

    # ── KPIs (README Section 2.4) ────────────────────────────
    d1, d2, d3, d4 = st.columns(4, gap="large")
    with d1:
        render_metric_card("Tổng bản ghi",    f"{len(df_d):,}",                         drone_sel)
    with d2:
        render_metric_card("Risk Score TB",   f"{df_d['risk_score'].mean():.1f}",        "Rủi ro trung bình")
    with d3:
        render_metric_card("Tỷ lệ High Risk", f"{df_d['is_high_risk'].mean()*100:.1f}%", "Tỷ lệ nguy hiểm")
    with d4:
        render_metric_card("Battery TB",      f"{df_d['battery_level'].mean():.0f}%",    "Dung lượng pin TB")

    st.divider()

    # ── Charts (README Section 2.4) ──────────────────────────
    a1, a2 = st.columns(2, gap="large")
    with a1:
        # README Section 2.4: risk score distribution
        render_section_label(f"Phân phối Risk Score — {drone_sel}")
        fig = px.histogram(df_d, x="risk_score", nbins=11,
                           color_discrete_sequence=[_C["accent"]], opacity=0.85)
        fig.update_traces(marker_line_width=0)
        st.plotly_chart(style_chart(fig, 340), use_container_width=True)

    with a2:
        # README Section 2.4: flight time vs battery level
        render_section_label(f"Flight Time vs Battery — {drone_sel}")
        sample = df_d.sample(min(1000, len(df_d)), random_state=42)
        fig2 = px.scatter(sample, x="flight_time", y="battery_level",
                          color="operation_risk", opacity=0.65,
                          color_discrete_map=_RISK_MAP)
        st.plotly_chart(style_chart(fig2, 340), use_container_width=True)

    # README Section 2.4: maintenance action distribution
    render_section_label("Phân bổ hành động bảo trì")
    mc = df_d["maintenance_action"].value_counts().reset_index()
    mc.columns = ["action", "count"]
    fig3 = px.pie(mc, names="action", values="count", hole=0.55,
                  color_discrete_sequence=_SEQ)
    fig3.update_traces(textfont_size=12)
    st.plotly_chart(style_chart(fig3, 380), use_container_width=True)


# ─────────────────────────────────────────────────────────────
# PAGE 5 — MODEL INFO  (extended — not in README, bonus page)
# ─────────────────────────────────────────────────────────────

elif page == "🤖  Model Info":
    render_page_title(
        "Model Info",
        "Accuracy, F1 per class, confusion matrix và feature importance của 3 RF models.",
    )
    render_banner(
        "Trang này sử dụng dữ liệu từ *_metrics.json và feature_importance.csv "
        "— được tạo khi chạy train_model.py.",
        "info",
    )

    # ── Accuracy overview (3 models) ────────────────────────
    render_section_label("Accuracy — 3 Models")
    model_defs = [
        ("operation_risk_model",     "Operation Risk"),
        ("maintenance_action_model", "Maintenance Action"),
        ("recommendation_model",     "Recommendation"),
    ]

    acc_cols    = st.columns(3, gap="large")
    all_metrics = []

    for col, (mname, _) in zip(acc_cols, model_defs):
        m = load_metrics(mname)
        all_metrics.append(m)
        with col:
            if m:
                render_model_accuracy_card(
                    m["target"], m["accuracy"],
                    m["cv_mean"], m["cv_std"],
                    m.get("trained_at", "—"),
                )
            else:
                render_banner(
                    f"Chưa có {mname}_metrics.json. Chạy train_model.py.", "warning"
                )

    # ── Per-class F1 + confusion matrix ─────────────────────
    st.divider()

    for (mname, display_name), m in zip(model_defs, all_metrics):
        if m is None:
            continue

        render_section_label(display_name)
        left, right = st.columns([1, 1], gap="large")

        with left:
            render_class_f1_table(
                m["classes"],
                m["per_class_f1"],
                m.get("per_class_precision"),
                m.get("per_class_recall"),
            )

        with right:
            fig_cm = render_confusion_matrix_heatmap(m["confusion_matrix"], m["classes"])
            st.plotly_chart(
                style_chart(fig_cm, 270),
                use_container_width=True,
                config={"displayModeBar": False},
            )

        st.markdown(
            f"""<div style="display:flex;gap:24px;flex-wrap:wrap;font-size:0.76rem;
                    color:var(--text-muted);margin:6px 0 18px;">
                <span>Train: <b style='color:var(--text-primary)'>{m['train_samples']:,}</b></span>
                <span>Test: <b style='color:var(--text-primary)'>{m['test_samples']:,}</b></span>
                <span>Trees: <b style='color:var(--text-primary)'>{m['n_estimators']}</b></span>
                <span>CV folds: <b style='color:var(--text-primary)'>{m['cv_folds']}</b></span>
                <span>Train time: <b style='color:var(--text-primary)'>{m.get('train_time_s','—')}s</b></span>
                <span>Trained: <b style='color:var(--text-primary)'>{m.get('trained_at','—')}</b></span>
            </div>""",
            unsafe_allow_html=True,
        )

    # ── Feature importance ───────────────────────────────────
    st.divider()
    render_section_label("Feature Importance  (averaged across 3 models — README Section 10)")

    fi_df = load_feature_importance()
    if fi_df is not None:
        st.plotly_chart(
            style_chart(render_feature_importance_chart(fi_df)),
            use_container_width=True,
            config={"displayModeBar": False},
        )
        st.caption("Source: Model/feature_importance.csv  ·  Generated by train_model.py")
    else:
        render_banner(
            "Chưa có file feature_importance.csv. Chạy `python train_model.py` để tạo.",
            "warning",
        )